### ISSUE TITLE
Localization of xcopy prevents build commands from working correctly on non-US systems

### ISSUE THREAD

**Issue by have-a-boy** [n-fisher/cookiecutter-rimworld-mod-development#10]
## Problem
The `echo F|xcopy ...` trick to automatically answer xcopy's "Is it a file or folder?" dialog unfortunately doesn't work correctly under non-US locales. In my case the dialog will ask me this question in german and awaits either "D" for "Datei" (file) or "V" for "Verzeichniss" (directory) as user input. This will either cause an error and prevent the project from being built, because xcopy received unexpected input, *or* it might coincidentally receive unintentionally valid input (like "D" meaning directory in english, but file in german) and just not copy anything. 
## Manual Workaround
Change the build event commands under project properties and replace the letters after the echo command according to your locales expectations.
## Possible Fix (not tested)
A bit of an undocumented hack that I discovered on Stackoverflow, is adding an asterisk (*) to the end of the path, which prevents xcopy from asking whether it's copying a file or a folder.

Maybe adding a notice about this issue to the readme would be enough to help out the international users of your template. :)

**Comment by n-fisher** [comment]
Hey apologies for missing this issue being filed for so long. I appreciate the bug report, and will look into localization-ambivalent implementations going forward.
