### ISSUE TITLE
RimWorld "RimWorldWin64" renaming causing multiple issues

### ISSUE THREAD

**Issue by have-a-boy** [n-fisher/cookiecutter-rimworld-mod-development#11]
## Problem
RimWorld executable name was changed to "RimWorldWin64.exe" and "RimWorldWin_Data" to "RimWorldWin64_Data" after 0.19/1.0 versions, causing an error when launching the application and multiple warnings for incorrectly referenced "Assembly-CSharp" and "UnityEngine" dll files.
## Manual Workaround

- Adjust "Start Action" paths for Debug and Release configurations under project properties to reflect the new executable name. 
- Remove incorrect References and add two new ones linking to the "Assembly-CSharp.dll" and "UnityEngine.dll" files in "...\RimWorldWin64_Data\Managed", then set "Copy Local" to "False" for both.

**Comment by n-fisher** [comment]
Good catch, I aim to simplify and update this package soon and will address this as well.
