### ISSUE TITLE
Template copy commands fail for Linux-based systems

### ISSUE THREAD

**Issue by lilwhitemouse** [n-fisher/cookiecutter-rimworld-mod-development#13]
## Problem
The cookie cutout doesn't work with Linux: all the copy commands are Windows.

## Do This
Linux has two different development compilers that I know of.  One uses PostBuildEvent (msbuild), one uses CustomCommands (mono-develop)

I can put together a pull request, if you like.

**Comment by L0laapk3** [comment]
I don't really actively maintain this anymore but pull requests are always
welcome.

>

**Comment by n-fisher** [comment]
Yeah while it would be awesome to have linux commands available, I don't have a machine I could put that together with. A PR would be welcome!

**Comment by L0laapk3** [comment]
Oops, sorry xD I didn't realise this wasn't my fork of the repo, I just replied directly to the email notification without looking at it. My bad!

**Comment by n-fisher** [comment]
You just said what I was going to, a week ahead of time. Thanks for the assist!

On Jul 21, 2019, at 11:35 AM, L0laapk3 <notifications@github.com> wrote:

Oops, sorry xD I didn't realise this wasn't my fork of the repo, I just replied directly to the email notification without looking at it. My bad!

**Comment by lilwhitemouse** [comment]
Okay; I'll work on it some, and see what I come up with.

I do have a few questions about the original design.  The separate names/About.xml/OutputPath for Release and Debug strikes me as ...unhelpful.  Especially for those of us who use #if DEBUG blocks during development/testing - having different mod names is actually kind of inconvenient?

**Comment by n-fisher** [comment]
It was a design pattern I developed and used for personal mods, but in hindsight can see it might add more complexity than the pattern is worth. What would be ideal behavior from your perspective?

And sorry for the delay, I'm just recovering from being sick. Out of curiosity, how are you writing/compiling/testing mods on a Unix platform? Never thought it was a viable dev platform for RW but would be interested in hearing about your implementation.

**Comment by lilwhitemouse** [comment]
From my perspective, I'd do away with all of the Release/Debug differences.  I think it adds complexity (and makes my life more difficult) without adding any benefit to my workflow, but then I didn't develop it around my own workflow ;)

I would have the top level mod-name, and then under About, only one About.xml.  (if I were feeling adventurous I would add a script to convert a Steam-format About.xml to both a GitHub-formatted one and an in-game formatted one, but that's another story for another day).  So there's much less to deal with or keep track of there.

And the debug and release .dlls would be treated identically - named the same and pulled to the Assemblies folder to replace the other depending on whether the developer made a release or debug build.  That way the developer can simply restart RimWorld (perhaps using the single-press restart key HugsLib provides) and the new behavior - with or without Debug-specific code - appears in game with no more effort that that.

(No worries re: delay - I know very much how that goes!  Plus we're doing this in our spare time, etc.  Which I am finally devoting a tiny bit of to this)

**Comment by lilwhitemouse** [comment]
Actually, once you take out that distinction, there's not a necessary reason for the copy commands at all, and the cookiecutter recipe as written works quite well on Linux.

**Comment by n-fisher** [comment]
Thanks for the input, I agree on all points. I've simplified a lot of the solution to make it more unopinionated :+1:

**Comment by lilwhitemouse** [comment]
Fix works well; much easier to not have to think about that at all!
