### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Rain1950** [n-fisher/cookiecutter-rimworld-mod-development#16]
So there is a known issue that some users (like me ) can't see " RimWorldWin"  to designate as startup project in Solution Explorer in VS 

 Can you help me and others fixing this issue / or by telling us how to fix it ?

Thats how it looks like in my VS ( it's in Polish cause  it's my first language , sorry for that ) 
https://imgur.com/a/EcEaCab

I'm sorry if  im just dumb and dont know basic stuff but im not proffesional and i followed all of the steps in the setup guide  and this is where i stopped because i can't go further with developing my mod called "SleepGun". 
Anyway i hope you will ever respond to this issue and help me .

**Comment by n-fisher** [comment]
Hi maksuu thanks for the report. 

That part of the instructions was actually for an old version and wouldn't have worked, so thanks for catching that. You can ignore that instruction (now removed), and going forward just build your project in Visual Studio and then launch Rimworld through Steam.
