### ISSUE TITLE
Cookiecutter Issue Assemblies

### ISSUE THREAD

**Issue by Rain1950** [n-fisher/cookiecutter-rimworld-mod-development#17]
Hello , i have a problem with cookiecutter. The problem is that in assemblies folder nothing creates after typing cookiecutter gh:n-fisher/cookiecutter-rimworld-mod-development in the cmd and following instructions. I already created few mods but now , when i generate folders, there is nothing in the assemblies folder. Maybe im doing something wrong or missing some steps but i dont know. 

can you explain what should i do or if its not my fault - fix it ?

**Comment by Rain1950** [comment]
nevermind , i should consider killing myself

**Comment by n-fisher** [comment]
Looks like you already figured it out, but you'll need to build your mods in Visual Studio if you're expecting compiled assemblies from any written C# code.
